MONGO_URI=
MONGO_DATABASE=
BASE_URL=

#use the same values as in elasticsearch/.env 
ELASTIC_USERNAME=
ELASTIC_PASSWORD=
ELASTIC_URI=https://localhost:

export MONGO_DATABASE MONGO_URI BASE_URL ELASTIC_USERNAME ELASTIC_PASSWORD ELASTIC_URI